# Generated by Django 2.2.3 on 2019-07-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_is_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_desc',
        ),
    ]
